### PR TITLE
Use fonts from node_modules instead of CDN

### PR DESCRIPTION
**Pull request by olafvanv**
I want to use this library inside a offline environment, but right now the library fetches the font-awesome font by using a CDN. This change will make sure it uses the font from the node_modules when building the library.

### CODE REVIEW

**Comment by kolkov** [comment]
Hi! Thanks for the PR. I will check it soon as possible.

**Comment by sipuja** [comment]
any update on it

**Comment by pietzschke** [comment]
Any updates on this?

**Comment by wyfrel** [comment]
any update on this ?

**Pull request merged**
