### PR TITLE
Fixed color picker popup position

### LINKED ISSUE #291: Color picker is badly positioned
As you can see in the following image, the color picker popup doesn't align with the trigger button:
image

### PR DESCRIPTION
**Pull request by EOussama**
This PR fixes #291 

On top of fixing the color picker popup position, I've run a formatted through the `angular-editor-toolbar.component.html` and `angular-editor-toolbar.component.scss` files.

### CODE REVIEW

**Comment by kolkov** [comment]
Thanks for PR! Update our PR please...

**Comment by EOussama** [comment]
> Thanks for PR! Update your PR please...

I fixed the conflict in the changes I worked on in `angular-editor-toolbar.component.html`, the rest of the conflicts are resulting from the updates that were present from your latest update. I'll wait for a fix from you before I re-update this PR.

**Comment by EOussama** [comment]
Hello @kolkov , can I request a quick PR review from you?

**Comment by kolkov** [comment]
Thanks for the PR. I will check it soon as possible.

**Pull request closed without merging**
