### PR TITLE
Inline Images if uploadUrl is not specified

### PR DESCRIPTION
**Pull request by fairmutex**
Added the feature that, if uploadUrl is not set, it falls back to loading the image inline.

<img src="data:image/jpeg;base64,/9j/4gIcSUND......

### CODE REVIEW

**Comment by mohyeid** [comment]
This would be a great feature. Was this PR reviewed? I am happy to help reviewing, but I wont have access to merge! What do we need to get this merged?

**Comment by mohyeid** [comment]
#88

**Comment by mateuspmello** [comment]
works for me this fix. thank you

**Comment by zijianhuang** [comment]
Great, and  this makes crop and resizing more desirable, since having a large image inline could be blowing up things.

**Comment by Salla-001** [comment]
Test-App-Flowchart

**Pull request merged**
