### PR TITLE
Fix <br> on deleting bold text and fix #122

### LINKED ISSUE #122: Bug: Changing formatting doesn't update the form value unless you change the text after
If you enter text into the angular-editor control and view the value in the form object, you will see the text (using a submit action). If you then highlight some of the text and bold it, but don't the text at all and check the value, the bold tags will not be there (this applies to changing any formatting). If you change the text and try it again, the bold or formatting tags will show up.

Using the demo app linked from this projects main page you can repo this issue. Open the example link on this projects home page. Type: "This is text." or anything else. Notice the HTML output says: "This is text." as expected. Highlight "text" and click bold. Notice the HTML Output doesn't change. Add a space to the end of the sentence and the bold tags appear.

### PR DESCRIPTION
**Pull request by alfredosalzillo**
- fixed empty <br> when delete all in some case.
  Example: when deleting a bold word if the word is the only in the textarea.

- fix text mutation not firing input event on EDGE (on the mutation of the highlighted text).
  BUG: #122

### CODE REVIEW

**Comment by kolkov** [comment]
Good example:
https://github.com/TinkoffCreditSystems/angular-contenteditable-accessor/blob/master/projects/angular-contenteditable-accessor/src/lib/contenteditable-value-accessor.ts

**Comment by alfredosalzillo** [comment]
In the example, the disconnect is also called if the input event works in the current browser, but the problem is that on EDGE, the input event is not fired in **some cases**, but it works. So we cannot disconnect the observer on input.

There are two solutions:

- we use only the MutationObserver and ignore the input in all the browsers
- we use only the MutationObserver and ignore the input only in IE and EDGE

**Comment by alfredosalzillo** [comment]
I see there was some problem during the commit, i close and reopen later when i fix this.

**Comment by kolkov** [comment]
And we need to consider such moment, that Microsoft at moment changes engine of EDGE to Chromium.

**Comment by kolkov** [comment]
https://www.theverge.com/2019/6/19/18692033/microsoft-chromium-edge-windows-7-8-available-download

**Comment by alfredosalzillo** [comment]
This is true. For now, I will only open a request for the 'br' problem.

**Comment by alfredosalzillo** [comment]
I have tested the library you linked on edge, and the problem of the #122 is not present.

> Good example:
> https://github.com/TinkoffCreditSystems/angular-contenteditable-accessor/blob/master/projects/angular-contenteditable-accessor/src/lib/contenteditable-value-accessor.ts

**Pull request closed without merging**
