### PR TITLE
#318 raw paste option added

### PR DESCRIPTION
**Pull request by Ryczko**
I added ,,rawPaste" option to the config, which allow us to pasting text without format #318

image

### CODE REVIEW

**Review by siva-pydakula — APPROVED** [review]

**Comment by siva-pydakula** [comment]
@kolkov can you please merge the above PR into Master branch because it will be useful for me.

**Comment by siva-pydakula** [comment]
Hi @kolkov  can you please merge the above changes and please release

**Comment by alisonflf** [comment]
i am in need of this change too @kolkov

**Comment by kolkov** [comment]
@alisonflf I think we need to add button to paste without format.

**Comment by alisonflf** [comment]
I understand.
in my case i hide most of buttons (ex: i only want bold and italic)
but since i cant get the paste event, the user may paste an text with a lot of undesired tags.
a clean on paste function would already help me in these cases.

maybe there's a way to achieve what i want, but i don't know how right now.

**Comment by kolkov** [comment]
@alisonflf OK I will try, but we need to update this PR to latest version of Editor.

**Comment by Ryczko** [comment]
@kolkov Done

**Pull request merged**
